### Importando excel inicial de sessões

In [3]:
import pandas as pd

df = pd.read_excel('../files/aulas.xlsx', sheet_name=0)

In [10]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df

,Carimbo de data/hora,nome cliente,Data,Status das aulas,Service,Comentários das aulas,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,2022-10-11 14:21:15.306,Jefferson,2022-10-06,done,canto_60,NaN,NaN,NaN,NaN
1,2022-10-11 14:21:58.152,Jefferson,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
2,2022-10-11 14:23:02.712,Jefferson,2022-09-23,done,canto_30,NaN,NaN,NaN,NaN
3,2022-10-11 14:24:15.055,Jefferson,2022-09-15,done,canto_30,NaN,NaN,NaN,NaN
4,2022-10-11 14:25:04.381,Jefferson,2022-09-08,done,canto_60,NaN,NaN,NaN,NaN
5,2022-10-11 14:25:04.381,Jefferson,2022-09-08,done,canto_30,Reposicão (30min),NaN,NaN,NaN
6,2022-10-11 14:27:17.021,Jefferson,2022-08-18,done,canto_30,NaN,NaN,NaN,NaN
7,2022-10-11 14:30:43.084,Jefferson,2022-08-25,done,canto_60,Eu cancelei (enxaqueca e febre),NaN,NaN,NaN
8,2022-10-11 14:35:47.578,Jefferson,2022-09-08,done,canto_30,30 min de aula (Reposicao do dia 25 agosto),NaN,NaN,NaN
9,2022-10-11 14:35:47.578,Jefferson,2022-09-08,done,canto_60,Reposição (60min),NaN,NaN,NaN
10,2022-10-11 14:40:13.061,Jefferson,2022-09-02,done,canto_30,Reposicao do dia 4 Agosto,NaN,NaN,NaN
11,2022-10-11 14:40:13.061,Jefferson,2022-09-02,done,canto_30,Reposição (30min),NaN,NaN,NaN
12,2022-10-11 16:37:33.068,Jefferson,2022-08-11,done,canto_60,NaN,NaN,NaN,NaN
13,2022-10-11 16:50:12.928,Jefferson,2022-08-04,done,canto_30,Problema no trabalho,NaN,NaN,NaN
14,2022-10-11 16:51:04.470,Jefferson,2022-07-28,done,canto_60,NaN,NaN,NaN,NaN
15,2022-10-11 16:51:46.601,Jefferson,2022-07-21,done,canto_60,NaN,NaN,NaN,NaN
16,2022-10-11 16:53:39.296,Jefferson,2022-07-14,done,canto_60,NaN,NaN,NaN,NaN
17,2022-10-11 16:54:03.637,Jefferson,2022-07-07,done,canto_30,NaN,NaN,NaN,NaN
18,2022-10-11 16:55:54.191,Jefferson,2022-06-30,done,canto_60,NaN,NaN,NaN,NaN
19,2022-10-11 17:00:51.088,Jefferson,2022-06-15,done,canto_60,NaN,NaN,NaN,NaN
20,2022-10-11 17:02:26.494,Jefferson,2022-06-10,done,canto_30,NaN,NaN,NaN,NaN
21,2022-10-11 17:02:43.801,Jefferson,2022-06-23,done,canto_30,NaN,NaN,NaN,NaN
22,2022-10-12 12:29:06.601,Jefferson,2022-06-02,done,canto_60,NaN,NaN,NaN,NaN
23,2022-10-13 17:26:25.712,luiz_rescke,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
24,2022-10-13 17:42:19.993,Luan,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
25,2022-10-13 17:42:19.993,Luan,2022-10-13,done,canto_30,Reposicão (30min),NaN,NaN,NaN
26,2022-10-13 17:43:45.123,Tati Balbino,2022-10-11,done,canto_60,NaN,NaN,NaN,NaN
27,2022-10-13 17:44:33.783,camila_merigui,2022-10-11,done,piano_60,NaN,NaN,NaN,NaN
28,2022-10-30 17:11:03.883,Vitor Sena,2022-10-29,done,canto_60,NaN,NaN,NaN,NaN
29,2022-10-30 17:12:23.600,ana_silva,2022-10-28,done,canto_30,NaN,NaN,NaN,NaN
30,2022-10-30 17:12:46.691,Breno Soler Amaral,2022-10-28,done,canto_60,NaN,NaN,NaN,NaN
31,2022-10-30 17:13:18.211,Jonathas,2022-10-28,done,canto_60,NaN,NaN,NaN,NaN
32,2022-10-30 17:18:39.846,Adriana Freud,2022-10-28,done,canto_60,NaN,NaN,NaN,NaN
33,2022-10-30 17:20:23.249,Victor,2022-10-28,done,canto_60,Aula Inaugural,NaN,NaN,NaN
34,2022-10-30 17:23:10.623,rodolpho_moraes,2022-10-27,done,canto_60,NaN,NaN,NaN,NaN
35,2022-10-30 17:23:44.622,Julia,2022-10-27,done,canto_60,NaN,NaN,NaN,NaN
36,2022-10-30 17:24:03.867,luiz_rescke,2022-10-27,done,canto_60,NaN,NaN,NaN,NaN
37,2022-10-30 17:24:28.989,Jefferson,2022-10-27,done,canto_30,NaN,NaN,NaN,NaN
38,2022-10-30 17:33:06.738,Luan,2022-10-27,done,canto_60,"Aula (60) + reposição 30' (dia 27out niver), r...",NaN,NaN,NaN
39,2022-10-30 17:37:10.549,Matheus Franco,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
40,2022-10-30 17:37:36.015,Raphael Stevan,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
41,2022-10-30 17:41:32.097,timbere_nogueira,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
42,2022-10-30 17:41:57.415,Ana Carolina,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
43,2022-10-30 17:42:28.967,Aline,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
44,2022-10-30 17:42:55.195,Marina Lopes,2022-10-25,done,canto_60,NaN,NaN,NaN,NaN
45,2022-10-30 17:44:34.802,Martha,2022-10-26,done,canto_60,NaN,NaN,NaN,NaN
46,2022-10-30 17:45:35.863,Joni Vitor,2022-10-25,done,canto_60,NaN,NaN,NaN,NaN
47,2022-10-30 17:47:43.245,camila_merigui,2022-10-25,done,piano_60,devo 5min,NaN,NaN,NaN
48,2022-10-30 17:48:06.496,camila_merigui,2022-10-25,done,canto_60,NaN,NaN,NaN,NaN
49,2022-10-30 17:49:17.489,Aline,2022-10-22,done,canto_60,NaN,NaN,NaN,NaN
50,2022-10-30 17:49:17.489,Aline,2022-10-22,done,canto_60,Reposição (60min),NaN,NaN,NaN
51,2022-10-30 17:50:43.111,Vitor Sena,2022-10-22,done,canto_60,NaN,NaN,NaN,NaN
52,2022-10-30 17:51:08.847,ana_flavia,2022-10-21,done,canto_60,NaN,NaN,NaN,NaN
53,2022-10-30 17:59:01.114,jacqueline_rodrigues,2022-10-21,done,canto_60,NaN,NaN,NaN,NaN
54,2022-10-30 18:06:12.237,Rafael Hosoi,2022-10-20,done,canto_60,NaN,NaN,NaN,NaN
55,2022-10-30 18:08:05.343,Adriana Freud,2022-10-21,done,canto_60,NaN,NaN,NaN,NaN
56,2022-10-30 18:08:31.276,Joni Vitor,2022-10-20,done,canto_60,NaN,NaN,NaN,NaN
57,2022-10-30 18:08:59.077,luiz_rescke,2022-10-20,done,canto_60,NaN,NaN,NaN,NaN
58,2022-10-30 18:09:23.221,Julia,2022-10-20,done,canto_30,NaN,NaN,NaN,NaN
59,2022-10-30 18:11:11.910,Matheus Franco,2022-10-19,done,canto_60,NaN,NaN,NaN,NaN
60,2022-10-30 18:12:33.672,Breno Soler Amaral,2022-10-20,done,canto_60,NaN,NaN,NaN,NaN
61,2022-10-30 18:13:03.284,Jefferson,2022-10-20,done,canto_60,NaN,NaN,NaN,NaN
62,2022-10-30 18:13:44.298,timbere_nogueira,2022-10-19,done,canto_60,NaN,NaN,NaN,NaN
63,2022-10-30 18:14:09.040,Marina Lopes,2022-10-18,done,canto_60,NaN,NaN,NaN,NaN
64,2022-10-30 18:16:06.573,camila_merigui,2022-10-18,done,canto_60,NaN,NaN,NaN,NaN
65,2022-10-30 18:55:10.062,camila_merigui,2022-10-18,done,piano_60,NaN,NaN,NaN,NaN
66,2022-10-30 19:13:10.716,Breno Soler Amaral,2022-10-14,done,canto_60,NaN,NaN,NaN,NaN
67,2022-10-30 19:20:20.171,ana_silva,2022-10-14,done,canto_30,NaN,NaN,NaN,NaN
68,2022-10-30 19:21:36.297,Raphael Salles,2022-10-17,done,canto_60,NaN,NaN,NaN,NaN
69,2022-10-30 19:27:18.527,jacqueline_rodrigues,2022-10-14,done,canto_60,NaN,NaN,NaN,NaN
70,2022-10-30 19:27:56.681,Ana Carolina,2022-10-14,done,canto_60,NaN,NaN,NaN,NaN
71,2022-10-30 19:28:42.839,Adriana Freud,2022-10-14,done,canto_60,Aula Inaugural,NaN,NaN,NaN
72,2022-10-30 20:31:59.802,luiz_rescke,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
73,2022-10-30 21:10:32.801,Julia,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
74,2022-10-30 21:11:01.238,timbere_nogueira,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
75,2022-10-30 21:23:58.845,leonardo_rodrigues,2022-10-13,done,canto_30,NaN,NaN,NaN,NaN
76,2022-10-30 21:24:22.092,leandro_bauch,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
77,2022-10-30 21:24:55.791,Luan,2022-10-13,done,canto_60,NaN,NaN,NaN,NaN
78,2022-10-30 21:24:55.791,Luan,2022-10-13,done,canto_30,Reposição (30min),NaN,NaN,NaN
79,2022-10-30 21:25:33.261,Jefferson,2022-10-13,done,canto_30,NaN,NaN,NaN,NaN
80,2022-10-30 21:27:37.692,Tati Balbino,2022-10-11,done,canto_60,NaN,NaN,NaN,NaN
81,2022-10-30 21:28:20.489,camila_merigui,2022-10-11,done,piano_60,NaN,NaN,NaN,NaN
82,2022-10-30 21:28:49.241,camila_merigui,2022-10-11,done,canto_60,NaN,NaN,NaN,NaN
83,2022-10-30 21:29:38.265,Julia,2022-10-10,done,canto_60,NaN,NaN,NaN,NaN
84,2022-10-30 21:37:30.476,Aline,2022-10-08,done,canto_60,NaN,NaN,NaN,NaN
85,2022-10-30 21:40:23.671,Martha,2022-10-08,done,canto_60,NaN,NaN,NaN,NaN
86,2022-10-30 21:52:24.327,Vitor Sena,2022-10-08,done,canto_60,NaN,NaN,NaN,NaN
87,2022-10-30 21:53:02.621,Ana Carolina,2022-10-07,done,canto_60,NaN,NaN,NaN,NaN
88,2022-10-30 21:53:32.447,luiz_rescke,2022-10-07,done,canto_60,NaN,NaN,NaN,NaN
89,2022-10-30 21:54:12.505,Rafael Hosoi,2022-10-06,done,canto_60,NaN,NaN,NaN,NaN
90,2022-10-30 21:54:42.307,leonardo_rodrigues,2022-10-06,done,canto_60,NaN,NaN,NaN,NaN
91,2022-10-30 21:55:26.870,Vitor Sena,2022-10-06,done,canto_60,Reposicao - aula de 15 out,NaN,NaN,NaN
92,2022-10-30 21:56:16.523,Luan,2022-10-06,done,canto_60,NaN,NaN,NaN,NaN
93,2022-10-30 21:56:51.239,leandro_bauch,2022-10-06,done,canto_60,NaN,NaN,NaN,NaN
94,2022-10-30 21:57:24.178,Matheus Franco,2022-10-05,done,canto_60,NaN,NaN,NaN,NaN
95,2022-10-30 21:57:56.836,Raphael Stevan,2022-10-05,done,canto_60,NaN,NaN,NaN,NaN
96,2022-10-30 21:58:20.287,timbere_nogueira,2022-10-05,done,canto_60,NaN,NaN,NaN,NaN
97,2022-10-30 21:58:48.435,Marina Lopes,2022-10-04,done,canto_60,NaN,NaN,NaN,NaN
98,2022-10-30 21:59:14.656,camila_merigui,2022-10-04,done,piano_60,NaN,NaN,NaN,NaN
99,2022-10-30 21:59:53.442,Vitor Sena,2022-10-01,done,canto_60,NaN,NaN,NaN,NaN
100,2022-10-30 22:00:26.525,Rafael Hosoi,2022-10-01,done,canto_60,NaN,NaN,NaN,NaN
101,2022-10-30 22:02:29.624,camila_merigui,2022-10-04,done,canto_60,NaN,NaN,NaN,NaN
102,2022-10-30 22:03:08.304,Raphael Salles,2022-10-03,done,canto_60,NaN,NaN,NaN,NaN
103,2022-10-30 22:03:49.816,ana_flavia,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
104,2022-10-30 22:05:36.328,Marina Lopes,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
105,2022-10-30 22:05:58.621,rodolpho_moraes,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
106,2022-10-31 16:59:30.843,luiz_rescke,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
107,2022-10-31 16:59:57.485,Jonathas,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
108,2022-10-31 17:09:47.512,jacqueline_rodrigues,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
109,2022-10-31 17:33:12.299,Jefferson,2022-09-30,done,canto_60,NaN,NaN,NaN,NaN
110,2022-10-31 17:34:10.644,leonardo_rodrigues,2022-09-29,done,canto_30,NaN,NaN,NaN,NaN
111,2022-10-31 17:40:37.246,Julia,2022-09-29,done,canto_30,NaN,NaN,NaN,NaN
112,2022-10-31 17:41:34.260,Joni Vitor,2022-09-29,done,canto_60,NaN,NaN,NaN,NaN
113,2022-10-31 20:07:02.177,Raphael Salles,2022-10-31,done,canto_60,NaN,NaN,NaN,NaN
114,2022-11-01 17:57:06.998,camila_merigui,2022-11-01,done,canto_60,NaN,NaN,NaN,NaN
115,2022-11-01 17:57:28.053,camila_merigui,2022-11-01,done,piano_60,NaN,NaN,NaN,NaN
116,2022-11-01 21:02:03.416,Vitor Sena,2022-11-01,done,canto_60,NaN,NaN,NaN,NaN
117,2022-11-02 11:42:37.090,Marina Lopes,2022-11-02,done,canto_60,pendente reposicao,NaN,NaN,NaN
118,2022-11-02 21:37:16.420,timbere_nogueira,2022-11-02,done,canto_60,sem voz,NaN,NaN,NaN
119,2022-11-02 21:38:02.624,Raphael Stevan,2022-11-02,done,canto_60,NaN,NaN,NaN,NaN
120,2022-11-02 21:38:30.107,Aline,2022-11-02,done,canto_60,NaN,NaN,NaN,NaN
121,2022-11-02 21:41:02.643,leandro_bauch,2022-09-29,done,canto_60,NaN,NaN,NaN,NaN
122,2022-11-02 21:41:42.390,Bruno,2022-09-28,done,canto_60,NaN,NaN,NaN,NaN
123,2022-11-02 21:42:33.287,Raphael Stevan,2022-09-28,done,canto_60,NaN,NaN,NaN,NaN
124,2022-11-02 21:44:02.772,timbere_nogueira,2022-09-28,done,canto_30,em Haver 30min (mal do estomago),NaN,NaN,NaN
125,2022-11-02 21:44:49.771,Ana Carolina,2022-09-28,done,canto_60,NaN,NaN,NaN,NaN
126,2022-11-02 21:45:31.715,Aline,2022-09-28,done,canto_60,NaN,NaN,NaN,NaN
127,2022-11-02 21:46:05.681,Tati Balbino,2022-09-27,done,canto_60,NaN,NaN,NaN,NaN
128,2022-11-02 21:46:37.304,camila_merigui,2022-09-27,done,canto_60,NaN,NaN,NaN,NaN
129,2022-11-02 21:47:13.389,camila_merigui,2022-09-27,done,piano_60,NaN,NaN,NaN,NaN
130,2022-11-02 21:47:48.570,leandro_bauch,2022-09-24,done,canto_60,NaN,NaN,NaN,NaN
131,2022-11-03 10:03:21.781,leandro_bauch,2022-11-03,done,canto_60,NaN,NaN,NaN,NaN
132,2022-11-03 11:15:22.083,Luan,2022-11-03,done,canto_60,NaN,NaN,NaN,NaN
133,2022-11-03 13:11:28.182,Jefferson,2022-11-03,done,canto_60,NaN,NaN,NaN,NaN
134,2022-11-03 15:35:46.349,luiz_rescke,2022-11-03,done,canto_60,NaN,NaN,NaN,NaN
135,2022-11-03 17:35:11.667,Julia,2022-11-03,done,canto_30,NaN,NaN,NaN,NaN
136,2022-11-03 18:35:29.680,rodolpho_moraes,2022-11-03,done,canto_60,Reposição (60min),NaN,NaN,NaN
137,2022-11-04 10:14:05.883,Victor,2022-11-04,done,canto_60,DEVEDOR,NaN,NaN,NaN
138,2022-11-04 10:56:44.988,Adriana Freud,2022-11-04,done,canto_60,NaN,NaN,NaN,NaN
139,2022-11-04 16:40:40.250,jacqueline_rodrigues,2022-11-04,done,canto_60,NaN,NaN,NaN,NaN
140,2022-11-04 16:41:36.277,Rafael Hosoi,2022-11-03,done,canto_60,NaN,NaN,NaN,NaN
141,2022-11-04 16:48:44.305,Ana Carolina,2022-11-04,done,canto_60,Reposição (60min),NaN,NaN,NaN
142,2022-11-04 19:10:34.822,Martha,2022-11-04,done,canto_60,NaN,NaN,NaN,NaN
143,2022-11-04 20:28:12.849,ana_flavia,2022-11-04,done,canto_30,NaN,NaN,NaN,NaN
144,2022-11-05 09:06:28.253,Vitor Sena,2022-11-05,done,canto_60,NaN,NaN,NaN,NaN
145,2022-11-09 13:19:39.897,camila_merigui,2022-11-08,done,canto_60,NaN,NaN,NaN,NaN
146,2022-11-09 16:20:26.634,Eder Felipe,2022-11-04,done,canto_60,NaN,NaN,NaN,NaN
147,2022-11-09 16:21:41.669,Vitor Sena,2022-09-24,done,canto_60,NaN,NaN,NaN,NaN
148,2022-11-09 16:22:21.172,ana_silva,2022-09-23,done,canto_60,NaN,NaN,NaN,NaN
149,2022-11-09 16:22:55.352,Breno Soler Amaral,2022-09-23,done,canto_60,NaN,NaN,NaN,NaN
150,2022-11-09 16:23:30.652,jacqueline_rodrigues,2022-09-23,done,canto_60,NaN,NaN,NaN,NaN
151,2022-11-09 16:43:07.050,Jefferson,2022-09-23,done,canto_30,NaN,NaN,NaN,NaN
152,2022-11-09 16:43:33.829,Aline,2022-09-23,done,canto_60,NaN,NaN,NaN,NaN
153,2022-11-09 16:44:14.578,Rafael Hosoi,2022-09-22,done,canto_60,NaN,NaN,NaN,NaN
154,2022-11-09 16:44:44.225,rodolpho_moraes,2022-09-22,done,canto_60,NaN,NaN,NaN,NaN
155,2022-11-09 16:45:33.795,Julia,2022-09-22,done,canto_60,Reposição (60min),NaN,NaN,NaN
156,2022-11-09 16:46:36.255,Matheus Franco,2022-09-21,done,canto_30,NaN,NaN,NaN,NaN
157,2022-11-09 16:48:35.501,timbere_nogueira,2022-09-21,done,canto_60,NaN,NaN,NaN,NaN
158,2022-11-09 16:48:58.316,Ana Carolina,2022-09-21,done,canto_60,NaN,NaN,NaN,NaN
159,2022-11-09 16:49:47.401,timbere_nogueira,2022-09-14,done,canto_60,NaN,NaN,NaN,NaN
160,2022-11-09 16:50:56.938,timbere_nogueira,2022-08-31,done,canto_60,NaN,NaN,NaN,NaN
161,2022-11-09 16:52:37.009,timbere_nogueira,2022-08-17,done,canto_60,NaN,NaN,NaN,NaN
162,2022-11-09 16:53:20.301,timbere_nogueira,2022-08-10,done,canto_60,NaN,NaN,NaN,NaN
163,2022-11-09 17:07:45.239,timbere_nogueira,2022-08-04,done,canto_60,NaN,NaN,NaN,NaN
164,2022-11-09 17:09:55.870,timbere_nogueira,2022-07-28,done,canto_60,reunião trabalho,NaN,NaN,NaN
165,2022-11-09 17:11:09.024,timbere_nogueira,2022-07-20,done,canto_60,NaN,NaN,NaN,NaN
166,2022-11-09 17:24:19.892,timbere_nogueira,2022-06-22,done,canto_60,NaN,NaN,NaN,NaN
167,2022-11-09 17:26:31.184,timbere_nogueira,2022-06-15,done,canto_60,NaN,NaN,NaN,NaN
168,2022-11-09 17:27:11.241,timbere_nogueira,2022-06-08,done,canto_60,NaN,NaN,NaN,NaN
169,2022-11-09 17:27:51.625,timbere_nogueira,2022-06-01,done,canto_60,NaN,NaN,NaN,NaN
170,2022-11-09 17:28:27.143,timbere_nogueira,2022-05-25,done,canto_60,NaN,NaN,NaN,NaN
171,2022-11-09 17:28:48.322,timbere_nogueira,2022-05-18,done,canto_60,NaN,NaN,NaN,NaN
172,2022-11-09 17:29:18.384,timbere_nogueira,2022-05-11,done,canto_60,NaN,NaN,NaN,NaN
173,2022-11-09 17:29:45.921,timbere_nogueira,2022-04-06,done,canto_60,NaN,NaN,NaN,NaN
174,2022-11-09 17:30:10.347,timbere_nogueira,2022-03-29,done,canto_60,NaN,NaN,NaN,NaN
175,2022-11-09 17:31:42.456,timbere_nogueira,2022-03-26,done,canto_60,NaN,NaN,NaN,NaN
176,2022-11-09 17:32:09.675,timbere_nogueira,2022-03-16,done,canto_60,NaN,NaN,NaN,NaN
177,2022-11-09 17:32:28.937,timbere_nogueira,2022-03-09,done,canto_60,NaN,NaN,NaN,NaN
178,2022-11-09 17:32:59.311,timbere_nogueira,2022-03-05,done,canto_60,NaN,NaN,NaN,NaN
179,2022-11-09 17:32:59.311,timbere_nogueira,2022-03-05,done,canto_30,Reposicão (30min),NaN,NaN,NaN
180,2022-11-09 17:34:12.160,timbere_nogueira,2022-02-08,done,canto_60,NaN,NaN,NaN,NaN
181,2022-11-09 17:36:42.120,timbere_nogueira,2022-02-23,done,canto_60,NaN,NaN,NaN,NaN
182,2022-11-09 17:36:42.120,timbere_nogueira,2022-02-23,done,canto_30,Reposicão (30min),NaN,NaN,NaN
183,2022-11-10 15:11:30.390,Joni Vitor,2022-11-10,done,canto_60,NaN,NaN,NaN,NaN
184,2022-11-10 15:36:23.011,luiz_rescke,2022-11-10,done,canto_60,NaN,NaN,NaN,NaN
185,2022-11-10 17:44:18.924,Martha,2022-11-10,done,canto_60,NaN,NaN,NaN,NaN
186,2022-11-15 10:06:58.832,Eder Felipe,2022-11-15,done,canto_60,NaN,NaN,NaN,NaN
187,2022-11-15 19:15:17.121,Marina Lopes,2022-11-15,done,canto_60,NaN,NaN,NaN,NaN
188,2022-11-20 16:47:39.781,Rafael Hosoi,2022-11-19,done,canto_60,NaN,NaN,NaN,NaN
189,2022-11-20 16:47:39.781,Rafael Hosoi,2022-11-19,done,canto_30,Reposicão (30min),NaN,NaN,NaN
190,2022-11-20 16:57:25.823,Eder Felipe,2022-11-18,done,canto_60,NaN,NaN,NaN,NaN
191,2022-11-20 16:58:32.208,Luan,2022-11-18,done,canto_60,NaN,NaN,NaN,NaN
192,2022-11-20 16:58:32.208,Luan,2022-11-18,done,canto_30,Reposicão (30min),NaN,NaN,NaN
193,2022-11-20 17:01:23.575,Martha,2022-11-17,done,canto_60,NaN,NaN,NaN,NaN
194,2022-11-20 17:10:43.057,Julia,2022-11-17,done,canto_30,NaN,NaN,NaN,NaN
195,2022-11-20 17:13:09.317,leandro_bauch,2022-11-17,done,canto_60,NaN,NaN,NaN,NaN
196,2022-11-20 17:13:48.212,Martha,2022-11-16,done,canto_60,Reposição (60min),NaN,NaN,NaN
197,2022-11-20 17:15:02.981,Raphael Stevan,2022-11-16,done,canto_60,NaN,NaN,NaN,NaN
198,2022-11-20 17:16:57.084,timbere_nogueira,2022-11-16,done,canto_60,NaN,NaN,NaN,NaN
199,2022-11-20 17:17:16.229,Ana Carolina,2022-11-16,done,canto_60,NaN,NaN,NaN,NaN
200,2022-11-20 17:17:42.402,leandro_bauch,2022-11-15,done,canto_60,Reposição (60min),NaN,NaN,NaN
201,2022-11-20 17:19:03.047,Marina Lopes,2022-11-15,done,canto_60,NaN,NaN,NaN,NaN
202,2022-11-20 17:26:53.909,camila_merigui,2022-11-15,done,piano_60,NaN,NaN,NaN,NaN
203,2022-11-20 17:27:47.316,camila_merigui,2022-11-15,done,canto_60,NaN,NaN,NaN,NaN
204,2022-11-20 17:28:16.257,Julia,2022-11-15,done,canto_60,NaN,NaN,NaN,NaN
205,2022-11-20 17:29:11.485,rodolpho_moraes,2022-11-10,done,canto_60,NaN,NaN,NaN,NaN
206,2022-11-20 17:30:25.188,Matheus Franco,2022-11-09,done,canto_60,NaN,NaN,NaN,NaN
207,2022-11-20 17:30:53.723,Raphael Stevan,2022-11-09,done,canto_60,NaN,NaN,NaN,NaN
208,2022-11-20 17:31:21.352,timbere_nogueira,2022-11-09,done,canto_60,NaN,NaN,NaN,NaN
209,2022-11-20 17:32:04.795,Adriana Freud,2022-11-09,done,canto_30,PENDENTE 30 MINUTOS,NaN,NaN,NaN
210,2022-11-20 17:32:26.250,Ana Carolina,2022-11-09,done,canto_60,NaN,NaN,NaN,NaN
211,2022-11-22 17:47:25.001,camila_merigui,2022-11-22,done,canto_60,NaN,NaN,problema de internet,NaN
212,2022-11-22 17:48:43.653,camila_merigui,2022-11-22,done,piano_60,NaN,NaN,NaN,NaN
213,2022-11-23 14:24:12.891,timbere_nogueira,2021-10-07,done,canto_60,NaN,NaN,NaN,NaN
214,2022-11-23 14:25:15.426,timbere_nogueira,2021-10-13,done,canto_60,NaN,NaN,NaN,NaN
215,2022-11-23 14:25:44.820,timbere_nogueira,2021-10-21,done,canto_60,NaN,NaN,NaN,NaN
216,2022-11-23 14:26:12.327,timbere_nogueira,2021-10-27,done,canto_60,NaN,NaN,NaN,NaN
217,2022-11-23 14:28:24.758,timbere_nogueira,2021-11-03,done,canto_60,rouco,NaN,NaN,NaN
218,2022-11-23 14:29:07.823,timbere_nogueira,2021-11-10,done,canto_60,NaN,NaN,NaN,NaN
219,2022-11-23 14:29:46.130,timbere_nogueira,2021-11-17,done,canto_60,NaN,NaN,NaN,NaN
220,2022-11-23 14:30:49.551,timbere_nogueira,2021-11-24,done,canto_60,NaN,NaN,NaN,NaN
221,2022-11-23 14:31:50.452,timbere_nogueira,2021-12-04,done,canto_60,NaN,NaN,NaN,NaN
222,2022-11-23 14:33:02.688,timbere_nogueira,2021-12-08,done,canto_60,viagem,NaN,NaN,NaN
223,2022-11-23 14:35:16.396,timbere_nogueira,2021-12-15,done,canto_60,NaN,NaN,NaN,NaN
224,2022-11-23 14:35:34.318,timbere_nogueira,2021-12-15,done,canto_30,Reposicão (30min),NaN,NaN,NaN
225,2022-11-23 14:36:19.071,timbere_nogueira,2021-12-22,done,canto_60,gripe,NaN,NaN,NaN
226,2022-11-23 14:41:42.184,timbere_nogueira,2021-12-29,done,canto_60,NaN,NaN,NaN,NaN
227,2022-11-23 14:43:32.160,timbere_nogueira,2022-01-05,done,canto_60,sinusite,NaN,NaN,NaN
228,2022-11-23 14:44:49.752,timbere_nogueira,2022-01-12,done,canto_60,NaN,NaN,NaN,NaN
229,2022-11-23 14:45:19.989,timbere_nogueira,2022-01-19,done,canto_60,NaN,NaN,NaN,NaN
230,2022-11-23 14:45:38.496,timbere_nogueira,2022-01-19,done,canto_30,Reposicão (30min),NaN,NaN,NaN
231,2022-11-23 14:46:03.482,timbere_nogueira,2022-01-26,done,canto_60,NaN,NaN,NaN,NaN
232,2022-11-23 14:47:06.253,timbere_nogueira,2022-02-01,done,canto_60,NaN,NaN,NaN,NaN
233,2022-11-23 14:47:24.693,timbere_nogueira,2022-02-01,done,canto_30,Reposicão (30min),NaN,NaN,NaN
234,2022-11-23 21:01:59.448,timbere_nogueira,2022-11-23,done,canto_60,NaN,NaN,NaN,NaN
235,2022-11-24 14:41:22.678,Jefferson,2022-11-24,done,canto_60,NaN,NaN,NaN,NaN

In [11]:

status = df['Status das aulas'].value_counts()
status

Status das aulas
done         2160
realizada     502
reposicao      25
saved          13
missed          6
faltou          5
Name: count, dtype: int64

In [ ]:
df[df['Status das aulas'] == 'faltou']

,Carimbo de data/hora,nome cliente,Data,Status das aulas,Service,Comentários das aulas,Unnamed: 6,Unnamed: 7,Unnamed: 8
2199,2025-09-22 15:43:47.886,nicoli_bozzella,2025-09-22,faltou,canto_60,NaN,NaN,NaN,NaN
2200,2025-09-22 15:44:02.300,nicoli_bozzella,2025-09-22,faltou,canto_30,NaN,NaN,NaN,NaN
2205,2025-09-25 10:48:43.760,giovanna_boni,2025-09-25,faltou,canto_45,NaN,NaN,NaN,NaN
2229,2025-10-03 12:29:26.762,leandro_bauch,2025-10-02,faltou,canto_60,NaN,NaN,NaN,NaN
2247,2025-10-10 14:49:55.462,gabriel_souza,2025-10-10,faltou,canto_60,mal de cama,NaN,NaN,NaN

In [20]:
df['Status2'] = df['Status das aulas'].apply(lambda x: 'realizada' if x in ('done', 'realizada', 'reposicao') else ('cancelada/cobrar' if x in ('faltou', 'missed') else 'ignorar'))

In [22]:
df['Status2'].value_counts()

Status2
realizada           2687
ignorar               18
cancelada/cobrar      11
Name: count, dtype: int64

In [24]:
df['Service'].value_counts()

Service
canto_60              1776
canto_30               569
canto_45               229
piano_60               134
Canto                    1
canto_60, canto_45       1
piano_30                 1
Name: count, dtype: int64