### Importando excel inicial de sessões

In [1]:
from reconciliation import get_sessions

invoicing = '2026-08'
file = '../files/aulas-2026-09-03.xlsx'

df = get_sessions(invoicing, file)
df

           nome cliente       Data     status  minutes     service status_row
2687         ana_flavia 2026-08-03  realizada       60  aula/canto         ok
2688     juliana_franco 2026-08-04  realizada       60  aula/canto         ok
2689        rui_miranda 2026-08-04  realizada       60  aula/canto         ok
2690     camila_merigui 2026-08-05  realizada       60  aula/canto         ok
2691    julia_(florida) 2026-08-05  realizada       45  aula/canto         ok
2692   timbere_nogueira 2026-08-05  realizada       60  aula/canto         ok
2693      giovanna_boni 2026-08-06  realizada       45  aula/canto         ok
2694     carol_teclarte 2026-08-07  realizada       45  aula/canto         ok
2695     juliana_franco 2026-08-11  realizada       60  aula/canto         ok
2696             miriam 2026-08-12  realizada       60  aula/canto         ok
2697   timbere_nogueira 2026-08-12  realizada       60  aula/canto         ok
2698     carol_teclarte 2026-08-13  realizada       60  aula/canto         ok
2699     camila_merigui 2026-08-13  realizada       60  aula/piano         ok
2700   timbere_nogueira 2026-08-13  reposicao       60  aula/canto         ok
2701     carol_teclarte 2026-08-14  realizada       45  aula/canto         ok
2702     juliana_franco 2026-08-19  realizada       60  aula/canto         ok
2703      andressa_lino 2026-08-20  realizada       30  aula/canto         ok
2704   timbere_nogueira 2026-08-20  realizada       60  aula/canto         ok
2705    julia_(florida) 2026-08-20  realizada       45  aula/canto         ok
2706  viviane_cerqueira 2026-08-21  realizada       60  aula/canto         ok
2707       sophia_lopes 2026-08-25  realizada       30  aula/canto         ok
2708       sophia_lopes 2026-08-25  realizada       30  aula/canto         ok
2709     juliana_franco 2026-08-25  realizada       60  aula/canto         ok
2710     camila_merigui 2026-08-27  realizada       60  aula/canto         ok
2711     camila_merigui 2026-08-27  realizada       60  aula/piano         ok
2712             miriam 2026-08-27  realizada       60  aula/canto         ok
2713             miriam 2026-08-27  realizada       30  aula/canto         ok
2714    julia_(florida) 2026-08-27  realizada       45  aula/canto         ok
2715  viviane_cerqueira 2026-08-28  realizada       60  aula/canto         ok
2716      giovanna_boni 2026-08-28  realizada       60  aula/canto         ok
2717         ana_flavia 2026-08-28  realizada       60  aula/canto         ok
2718  viviane_cerqueira 2026-08-29  reposicao       60  aula/canto         ok
2722    nicoli_bozzella 2026-08-31  realizada       60  aula/canto         ok

In [4]:
df[['nome cliente', 'service', 'minutes', 'status_row']].value_counts()

nome cliente       service     minutes  status_row
juliana_franco     aula/canto  60       ok            4
timbere_nogueira   aula/canto  60       ok            4
julia_(florida)    aula/canto  45       ok            3
viviane_cerqueira  aula/canto  60       ok            3
ana_flavia         aula/canto  60       ok            2
camila_merigui     aula/canto  60       ok            2
carol_teclarte     aula/canto  45       ok            2
miriam             aula/canto  60       ok            2
camila_merigui     aula/piano  60       ok            2
sophia_lopes       aula/canto  30       ok            2
rui_miranda        aula/canto  60       ok            1
giovanna_boni      aula/canto  45       ok            1
carol_teclarte     aula/canto  60       ok            1
andressa_lino      aula/canto  30       ok            1
miriam             aula/canto  30       ok            1
giovanna_boni      aula/canto  60       ok            1
nicoli_bozzella    aula/canto  60       ok            1
Name: count, dtype: int64

In [5]:
from reconciliation import get_invoices

vendor = 'estudio_amelia'
month = '2026-08'

df_invoices = get_invoices(vendor=vendor, invoicing=month)
df_invoices

,customer,invoicing,amount,description,quantity,price,mes_referencia,minutos,tipo_servico,status_row
0,carol_teclarte,2026-08-02,392,aulas de canto de 45 minutos em agosto de 2026,4,98,08/2026,45.0,aula/canto,ok
1,camila_merigui,2026-08-02,588,aulas de canto de 60 minutos em junho de 2026,3,98,06/2026,60.0,aula/canto,ok
2,camila_merigui,2026-08-02,588,aulas de piano de 60 minutos em junho de 2026,3,98,06/2026,60.0,aula/piano,ok
3,rui_faco,2026-08-02,240,aulas de canto de 60 minutos em agosto de 2026,2,120,08/2026,60.0,aula/canto,ok
4,solange_lopes,2026-08-02,360,aulas de canto de 30 minutos em julho de 2026,2,60,07/2026,30.0,aula/canto,ok
5,solange_lopes,2026-08-02,360,aulas de canto de 60 minutos em julho de 2026,2,120,07/2026,60.0,aula/canto,ok
6,alessandra_galassi,2026-08-02,220,aulas de canto de 60 minutos em julho de 2026,2,110,07/2026,60.0,aula/canto,ok
7,miriam_silva,2026-08-02,220,aulas de canto de 60 minutos em julho de 2026,2,110,07/2026,60.0,aula/canto,ok
8,andressa_lino,2026-08-05,70,aula de canto de 30 minutos em 27/08/2026,1,70,08/2026,30.0,aula/canto,ok
9,juliana_franco,2026-08-02,440,aulas de canto de 60 minutos em julho de 2026,4,110,07/2026,60.0,aula/canto,ok
10,andressa_lino,2026-08-05,70,aula de canto de 30 minutos em 20/08/2026,1,70,08/2026,30.0,aula/canto,ok
11,andrea_silva,2026-08-02,392,aulas de canto de 45 minutos em julho de 2026,4,98,07/2026,45.0,aula/canto,ok
12,zenith_bozzella,2026-08-17,240,aulas de canto de 60 minutos em agosto de 2026,2,120,08/2026,60.0,aula/canto,ok
13,timbere,2026-08-02,440,aulas de canto de 60 minutos em agosto de 2026,4,110,08/2026,60.0,aula/canto,ok
14,sandra_oliveira,2026-08-01,100,edição de músicas para aula em 01/08/2026,1,100,08/2026,NaN,NaN,error
15,ana_flavia,2026-08-02,220,aulas de canto de 60 minutos em julho de 2026,2,110,07/2026,60.0,aula/canto,ok
16,andressa_lino,2026-08-20,70,hora adicional de aulas de canto de 30 minutos...,1,70,08/2026,30.0,aula/canto,ok
17,sheila_silva,2026-08-28,150,aulas de canto avulsa de 60 minutos prevista p...,1,150,09/2026,60.0,aula/canto,ok
18,helena_batista,2026-08-27,210,aulas de canto de 30 minutos previstas para os...,3,70,08/2026,30.0,aula/canto,ok
19,viviane_cerqueira,2026-08-02,440,aulas de canto de 60 minutos em agosto de 2026,4,110,08/2026,60.0,aula/canto,ok