In [2]:
vendor = 'estudio_amelia'
invoicing = '2026-08'
file = '../files/aulas-2026-09-03.xlsx'

In [ ]:
from reconciliation import get_sessions

df_raw, df_sessions = get_sessions(invoicing, file)
df_sessions.to_csv("../files/sessions.csv")

,customer,Data,status,minutes,service,status_row,status_type,month
2649,sophia_lopes,2026-07-07,realizada,60,aula/canto,ok,realizada/reposicao,2026-07
2650,juliana_franco,2026-07-07,realizada,60,aula/canto,ok,realizada/reposicao,2026-07
2651,giovanna_boni,2026-07-08,realizada,60,aula/canto,ok,realizada/reposicao,2026-07
2652,timbere_nogueira,2026-07-08,realizada,60,aula/canto,ok,realizada/reposicao,2026-07
2653,juliana_franco,2026-07-09,realizada,60,aula/canto,ok,realizada/reposicao,2026-07
...,...,...,...,...,...,...,...,...
2716,giovanna_boni,2026-08-28,realizada,60,aula/canto,ok,realizada/reposicao,2026-08
2717,ana_flavia,2026-08-28,realizada,60,aula/canto,ok,realizada/reposicao,2026-08
2718,viviane_cerqueira,2026-08-29,reposicao,60,aula/canto,ok,realizada/reposicao,2026-08
2722,nicoli_bozzella,2026-08-31,realizada,60,aula/canto,ok,realizada/reposicao,2026-08
2732,stefanie,2026-07-23,realizada,60,aula/canto,ok,realizada/reposicao,2026-07

In [20]:
df_raw[df_raw['customer'] == 'nicoli_bozzella']

,customer,Data,status,minutes,service,status_row,status_type,month
2722,nicoli_bozzella,2026-08-31,realizada,60,aula/canto,ok,realizada/reposicao,2026-08

In [9]:
from reconciliation import get_invoices

df_invoices = get_invoices(vendor=vendor, invoicing=invoicing)
df_invoices.to_csv("../files/invoices.csv")
df_invoices

,customer,invoicing,due,payment,amount,description,preview,price,month,minutes,service,status_row
0,carol_teclarte,2026-08-02,2026-08-05,paid,392,aulas de canto de 45 minutos em agosto de 2026,4,98,2026-08,45.0,aula/canto,ok
1,camila_merigui,2026-08-02,2026-08-05,paid,588,aulas de canto de 60 minutos em julho de 2026,3,98,2026-07,60.0,aula/canto,ok
2,camila_merigui,2026-08-02,2026-08-05,paid,588,aulas de piano de 60 minutos em julho de 2026,3,98,2026-07,60.0,aula/piano,ok
3,rui_miranda,2026-08-02,2026-08-10,paid,240,aulas de canto de 60 minutos em agosto de 2026,2,120,2026-08,60.0,aula/canto,ok
4,sophia_lopes,2026-08-02,2026-08-17,paid,360,aulas de canto de 30 minutos em julho de 2026,2,60,2026-07,30.0,aula/canto,ok
5,sophia_lopes,2026-08-02,2026-08-17,paid,360,aulas de canto de 60 minutos em julho de 2026,2,120,2026-07,60.0,aula/canto,ok
6,giovanna_boni,2026-08-02,2026-08-20,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
7,miriam,2026-08-02,2026-08-10,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
8,andressa_lino,2026-08-05,2026-09-03,paid,70,aula de canto de 30 minutos em 27/08/2026,1,70,2026-08,30.0,aula/canto,ok
9,juliana_franco,2026-08-02,2026-08-17,paid,440,aulas de canto de 60 minutos em julho de 2026,4,110,2026-07,60.0,aula/canto,ok
10,andressa_lino,2026-08-05,2026-08-20,paid,70,aula de canto de 30 minutos em 20/08/2026,1,70,2026-08,30.0,aula/canto,ok
11,julia_(florida),2026-08-02,2026-08-20,paid,392,aulas de canto de 45 minutos em julho de 2026,4,98,2026-07,45.0,aula/canto,ok
12,nicoli_bozzella,2026-08-17,2026-08-18,paid,240,aulas de canto de 60 minutos em agosto de 2026,2,120,2026-08,60.0,aula/canto,ok
13,timbere_nogueira,2026-08-02,2026-08-27,paid,440,aulas de canto de 60 minutos em agosto de 2026,4,110,2026-08,60.0,aula/canto,ok
14,sandra_oliveira,2026-08-01,2026-08-01,paid,100,edição de músicas para aula em 01/08/2026,1,100,2026-08,NaN,NaN,error
15,ana_flavia,2026-08-02,2026-08-05,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
16,andressa_lino,2026-08-20,2026-08-27,paid,70,hora adicional de aulas de canto de 30 minutos...,1,70,2026-08,30.0,aula/canto,ok
17,helena_batista,2026-08-27,2026-08-28,paid,210,aulas de canto de 30 minutos previstas para os...,3,70,2026-08,30.0,aula/canto,ok
18,viviane_cerqueira,2026-08-02,2026-08-17,paid,440,aulas de canto de 60 minutos em agosto de 2026,4,110,2026-08,60.0,aula/canto,ok
19,sheila_silva,2026-08-28,2026-08-31,paid,150,aulas de canto avulsa de 60 minutos prevista p...,1,150,2026-09,60.0,aula/canto,ok

In [4]:
from reconciliation import reconciliate
df_rec = reconciliate(df_invoices, df_sessions)

In [5]:
from reconciliation import extras

df_extras = extras(df_invoices, df_sessions, invoicing_month=invoicing)
df_extras

      month        customer     service  minutes  done
11  2026-08   giovanna_boni  aula/canto       45     1
12  2026-08  carol_teclarte  aula/canto       60     1
16  2026-08          miriam  aula/canto       30     1

In [6]:
df_rec[(df_rec['month'] == '2026-07') & (df_rec['status_row'] == 'ok') & (df_rec['preview'] != df_rec['done']) ]

,month,status_row,customer,service,minutes,payment,preview,done,balance
4,2026-07,ok,sophia_lopes,aula/canto,30.0,paid,2,1,1
9,2026-07,ok,juliana_franco,aula/canto,60.0,paid,4,5,-1
11,2026-07,ok,julia_(florida),aula/canto,45.0,paid,4,3,1
15,2026-07,ok,ana_flavia,aula/canto,60.0,paid,2,1,1

In [7]:
df_rec[(df_rec['month'] == '2026-08') & (df_rec['status_row'] == 'ok') & (df_rec['preview'] != df_rec['done'])]

,month,status_row,customer,service,minutes,payment,preview,done,balance
0,2026-08,ok,carol_teclarte,aula/canto,45.0,paid,4,2,2
3,2026-08,ok,rui_miranda,aula/canto,60.0,paid,2,1,1
12,2026-08,ok,nicoli_bozzella,aula/canto,60.0,paid,2,1,1
18,2026-08,ok,helena_batista,aula/canto,30.0,paid,3,0,3
19,2026-08,ok,viviane_cerqueira,aula/canto,60.0,paid,4,3,1